(() => {
  'use strict';
  const canvas=document.getElementById('trackCanvas'),frame=document.getElementById('canvasFrame'),ctx=canvas.getContext('2d');
  const ui={trackName:document.getElementById('trackName'),profileName:document.getElementById('profileName'),profileCode:document.getElementById('profileCode'),profileCountry:document.getElementById('profileCountry'),profileLocation:document.getElementById('profileLocation'),profileDirection:document.getElementById('profileDirection'),profileCodeDisplay:document.getElementById('profileCodeDisplay'),profileCountryDisplay:document.getElementById('profileCountryDisplay'),saveState:document.getElementById('saveState'),length:document.getElementById('lengthValue'),turns:document.getElementById('turnValue'),width:document.getElementById('trackWidth'),widthValue:document.getElementById('widthValue'),numberToggle:document.getElementById('numberToggle'),autoConnectToggle:document.getElementById('autoConnectToggle'),lineToggle:document.getElementById('lineToggle'),drawHint:document.getElementById('drawHint'),toast:document.getElementById('toast'),undo:document.getElementById('undoBtn'),redo:document.getElementById('redoBtn')};
  const palettes={classic:['#ffe000','#ff3045','#19c7f5'],sunset:['#ffb000','#ff5e76','#9b5cff'],mono:['#b6bac0','#68707a','#20252b']};
  const presets={
    technical:[[205,140],[318,105],[430,120],[535,175],[610,145],[690,190],[670,275],[735,315],[700,400],[600,435],[545,395],[465,455],[375,430],[330,365],[250,380],[165,325],[130,245]],
    speed:[[180,185],[330,110],[510,120],[710,205],[785,330],[690,430],[490,455],[305,425],[150,330],[120,240]],
    street:[[245,120],[510,120],[510,205],[690,205],[690,385],[555,385],[555,460],[330,460],[330,350],[170,350],[170,215],[245,215]]
  };
  const defaultState=()=>({name:'ORBITAL GRAND PRIX',profile:{code:'ORB',country:'IRN',location:'TEHRAN, IRAN',direction:'clockwise'},width:22,palette:'classic',showNumbers:true,autoConnect:true,showLine:true,closed:true,points:presets.technical.map(([x,y])=>({x,y})),markers:[{type:'drs',t:.10,label:'DRS\nZONE 1'},{type:'drs',t:.56,label:'DRS\nZONE 2'},{type:'trap',t:.78,label:'SPEED\nTRAP'}]});
  const clone=value=>JSON.parse(JSON.stringify(value));
  function loadState(){try{return JSON.parse(localStorage.getItem('apex-track-state'))}catch{return null}}
  let state=loadState()||defaultState(),mode='edit',history=[],future=[],dragging=-1,hoverPoint=-1,pointer={x:0,y:0},toastTimer;
  if(typeof state.autoConnect!=='boolean')state.autoConnect=true;
  if(!state.profile)state.profile={code:'ORB',country:'IRN',location:'TEHRAN, IRAN',direction:'clockwise'};

  function save(){ui.saveState.classList.add('saving');ui.saveState.lastChild.textContent=' SAVING';localStorage.setItem('apex-track-state',JSON.stringify(state));setTimeout(()=>{ui.saveState.classList.remove('saving');ui.saveState.lastChild.textContent=' SAVED'},360)}
  function commit(previous){if(previous)history.push(previous);if(history.length>50)history.shift();future=[];save();updateUI()}
  function notify(message){clearTimeout(toastTimer);ui.toast.textContent=message;ui.toast.classList.add('show');toastTimer=setTimeout(()=>ui.toast.classList.remove('show'),1800)}
  function resize(){const rect=frame.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.floor(rect.width*dpr));canvas.height=Math.max(1,Math.floor(rect.height*dpr));canvas.style.width=rect.width+'px';canvas.style.height=rect.height+'px';ctx.setTransform(dpr,0,0,dpr,0,0);draw()}
  function view(){const w=frame.clientWidth,h=frame.clientHeight,scale=Math.min(w/900,h/560);return{scale,ox:(w-900*scale)/2,oy:(h-560*scale)/2}}
  function toWorld(event){const r=canvas.getBoundingClientRect(),v=view();return{x:(event.clientX-r.left-v.ox)/v.scale,y:(event.clientY-r.top-v.oy)/v.scale}}

  function roundedPath(points,closed=true){const path=new Path2D();if(!points.length)return path;if(points.length<3){path.moveTo(points[0].x,points[0].y);points.slice(1).forEach(p=>path.lineTo(p.x,p.y));return path}const count=points.length,get=i=>closed?points[(i+count)%count]:points[Math.max(0,Math.min(count-1,i))];path.moveTo(points[0].x,points[0].y);const segments=closed?count:count-1;for(let i=0;i<segments;i++){const p0=get(i-1),p1=get(i),p2=get(i+1),p3=get(i+2),t=.72;path.bezierCurveTo(p1.x+(p2.x-p0.x)*t/6,p1.y+(p2.y-p0.y)*t/6,p2.x-(p3.x-p1.x)*t/6,p2.y-(p3.y-p1.y)*t/6,p2.x,p2.y)}if(closed)path.closePath();return path}
  function sampleTrack(samples=300){const pts=state.points;if(pts.length<2)return pts.map(p=>({...p}));const out=[],limit=state.closed?samples:Math.max(2,Math.floor(samples*(pts.length-1)/pts.length));for(let i=0;i<limit;i++){const u=(i/(state.closed?samples:limit-1))*(state.closed?pts.length:pts.length-1),n=Math.min(pts.length-2,Math.floor(u)),t=u-Math.floor(u),get=k=>state.closed?pts[(k+pts.length)%pts.length]:pts[Math.max(0,Math.min(pts.length-1,k))],p0=get(n-1),p1=get(n),p2=get(n+1),p3=get(n+2),t2=t*t,t3=t2*t;out.push({x:.5*((2*p1.x)+(-p0.x+p2.x)*t+(2*p0.x-5*p1.x+4*p2.x-p3.x)*t2+(-p0.x+3*p1.x-3*p2.x+p3.x)*t3),y:.5*((2*p1.y)+(-p0.y+p2.y)*t+(2*p0.y-5*p1.y+4*p2.y-p3.y)*t2+(-p0.y+3*p1.y-3*p2.y+p3.y)*t3)})}return out}
  function drawGrid(w,h){if(!document.getElementById('gridBtn').classList.contains('active'))return;ctx.save();ctx.strokeStyle='#e7e7e3';ctx.lineWidth=1;for(let x=0;x<w;x+=32){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=32){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.restore()}
  function strokeSegment(samples,start,end,color,width,closed){if(!samples.length)return;const n=samples.length,a=Math.floor(start*(closed?n:n-1)),b=Math.floor(end*(closed?n:n-1));ctx.beginPath();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.lineJoin='round';ctx.moveTo(samples[a%n].x,samples[a%n].y);for(let i=a+1;i<=b;i++){const p=samples[closed?i%n:Math.min(i,n-1)];ctx.lineTo(p.x,p.y)}ctx.stroke()}
  function drawSectorDivisions(samples){if(samples.length<8)return;const colors=palettes[state.palette]||palettes.classic;[0,.334,.667].forEach((t,index)=>{const n=samples.length,i=Math.min(n-1,Math.floor(t*(state.closed?n:n-1))),p=samples[i],before=state.closed?(i-3+n)%n:Math.max(0,i-3),after=state.closed?(i+3)%n:Math.min(n-1,i+3),a=samples[before],b=samples[after],angle=Math.atan2(b.y-a.y,b.x-a.x),nx=Math.cos(angle+Math.PI/2),ny=Math.sin(angle+Math.PI/2),side=p.x<450?-1:1,x=p.x+nx*side*(state.width+14),y=p.y+ny*side*(state.width+14),half=Math.max(2,state.width/2-3);ctx.save();ctx.strokeStyle='#111318';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p.x-nx*half,p.y-ny*half);ctx.lineTo(p.x+nx*half,p.y+ny*half);ctx.stroke();ctx.fillStyle='#111318';ctx.fillRect(x-15,y-9,30,18);ctx.fillStyle=colors[index];ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='800 8px Manrope,Arial';ctx.fillText(`S${index+1}`,x,y+.5);ctx.restore()})}
  const pointOnTrack=(t,samples)=>samples[Math.floor((((t%1)+1)%1)*samples.length)%samples.length];
  function drawMarker(marker,samples){const p=pointOnTrack(marker.t,samples),drs=marker.type==='drs',color=drs?'#20c52b':'#ed00de',side=p.x<450?-1:1,boxW=drs?108:86,boxH=43;let bx=p.x+side*45-(side<0?boxW:0),by=p.y+(p.y<260?52:-78);bx=Math.max(12,Math.min(888-boxW,bx));by=Math.max(12,Math.min(548-boxH,by));ctx.save();ctx.strokeStyle=color;ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x,by+boxH/2);ctx.lineTo(side<0?bx+boxW:bx,by+boxH/2);ctx.stroke();ctx.fillStyle=color;ctx.beginPath();ctx.arc(p.x,p.y,6,0,Math.PI*2);ctx.fill();ctx.fillRect(bx,by,boxW,boxH);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='800 12px Manrope,Arial';marker.label.split('\n').forEach((line,i)=>ctx.fillText(line,bx+boxW/2,by+15+i*13));ctx.restore()}
  function drawStartFinish(samples){if(samples.length<2)return;const p=samples[0],q=samples[3],angle=Math.atan2(q.y-p.y,q.x-p.x),size=4;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(angle);for(let r=0;r<2;r++)for(let c=0;c<5;c++){ctx.fillStyle=(r+c)%2?'#fff':'#111318';ctx.fillRect(-size*2.5+c*size,-state.width/2+r*size,size,size)}ctx.restore()}

  function draw(){const w=frame.clientWidth,h=frame.clientHeight,v=view();ctx.clearRect(0,0,w,h);ctx.fillStyle='#f5f5f2';ctx.fillRect(0,0,w,h);drawGrid(w,h);ctx.save();ctx.translate(v.ox,v.oy);ctx.scale(v.scale,v.scale);const pts=state.points;if(pts.length){const path=roundedPath(pts,state.closed);ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#101218';ctx.lineWidth=state.width+10;ctx.stroke(path);ctx.strokeStyle='#f8f8f6';ctx.lineWidth=state.width;ctx.stroke(path);const samples=sampleTrack();if(state.showLine&&state.closed&&samples.length){const colors=palettes[state.palette]||palettes.classic;strokeSegment(samples,0,.334,colors[0],4);strokeSegment(samples,.334,.667,colors[1],4);strokeSegment(samples,.667,1,colors[2],4)}if(state.closed&&samples.length){drawStartFinish(samples);state.markers.forEach(m=>drawMarker(m,samples))}if(state.showNumbers&&state.closed){pts.forEach((p,i)=>{const prev=pts[(i-1+pts.length)%pts.length],next=pts[(i+1)%pts.length];let nx=p.x*2-prev.x-next.x,ny=p.y*2-prev.y-next.y,len=Math.hypot(nx,ny)||1;nx/=len;ny/=len;const x=p.x+nx*(state.width+8),y=p.y+ny*(state.width+8);ctx.fillStyle='#111318';ctx.beginPath();ctx.arc(x,y,11,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=1;ctx.stroke();ctx.fillStyle='#fff';ctx.font='800 8px Manrope,Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(i+1).padStart(2,'0'),x,y+.5)})}if(mode==='edit'||mode==='draw'){pts.forEach((p,i)=>{ctx.beginPath();ctx.arc(p.x,p.y,i===hoverPoint||i===dragging?7:4,0,Math.PI*2);ctx.fillStyle=i===hoverPoint||i===dragging?'#d8ff38':'#111318';ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.stroke()})}if(mode==='draw'&&!state.closed&&pts.length){ctx.setLineDash([6,6]);ctx.strokeStyle='#777';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(pts[pts.length-1].x,pts[pts.length-1].y);ctx.lineTo(pointer.x,pointer.y);ctx.stroke();ctx.setLineDash([])}}ctx.restore()}

  draw=function(){
    const w=frame.clientWidth,h=frame.clientHeight,v=view();
    ctx.clearRect(0,0,w,h);ctx.fillStyle='#f5f5f2';ctx.fillRect(0,0,w,h);drawGrid(w,h);
    ctx.save();ctx.translate(v.ox,v.oy);ctx.scale(v.scale,v.scale);
    const pts=state.points;
    if(pts.length){
      const path=roundedPath(pts,state.closed);
      ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#101218';ctx.lineWidth=state.width+10;ctx.stroke(path);
      ctx.strokeStyle='#f8f8f6';ctx.lineWidth=state.width;ctx.stroke(path);
      const samples=sampleTrack();
      if(state.showLine&&samples.length>1){
        const colors=palettes[state.palette]||palettes.classic;
        strokeSegment(samples,0,.334,colors[0],4,state.closed);
        strokeSegment(samples,.334,.667,colors[1],4,state.closed);
        strokeSegment(samples,.667,1,colors[2],4,state.closed);
        drawSectorDivisions(samples);
      }
      if(state.closed&&samples.length){drawStartFinish(samples);state.markers.forEach(m=>drawMarker(m,samples))}
      if(state.showNumbers){
        const center=pts.reduce((sum,p)=>({x:sum.x+p.x/pts.length,y:sum.y+p.y/pts.length}),{x:0,y:0});
        pts.forEach((p,i)=>{
          const prev=pts[state.closed?(i-1+pts.length)%pts.length:Math.max(0,i-1)],next=pts[state.closed?(i+1)%pts.length:Math.min(pts.length-1,i+1)];
          let tx=next.x-prev.x,ty=next.y-prev.y,nx=-ty,ny=tx,len=Math.hypot(nx,ny)||1;nx/=len;ny/=len;
          if(nx*(p.x-center.x)+ny*(p.y-center.y)<0){nx*=-1;ny*=-1}
          const x=p.x+nx*(state.width+8),y=p.y+ny*(state.width+8);
          ctx.fillStyle='#111318';ctx.beginPath();ctx.arc(x,y,11,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=1;ctx.stroke();
          ctx.fillStyle='#fff';ctx.font='800 8px Manrope,Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(i+1).padStart(2,'0'),x,y+.5);
        });
      }
      if(mode==='edit'||mode==='draw')pts.forEach((p,i)=>{ctx.beginPath();ctx.arc(p.x,p.y,i===hoverPoint||i===dragging?7:4,0,Math.PI*2);ctx.fillStyle=i===hoverPoint||i===dragging?'#d8ff38':'#111318';ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.stroke()});
      if(mode==='draw'&&!state.closed&&pts.length){ctx.setLineDash([6,6]);ctx.strokeStyle='#777';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(pts[pts.length-1].x,pts[pts.length-1].y);ctx.lineTo(pointer.x,pointer.y);ctx.stroke();ctx.setLineDash([]);if(state.autoConnect&&pts.length>2){ctx.strokeStyle='#d8ff38';ctx.lineWidth=2;ctx.beginPath();ctx.arc(pts[0].x,pts[0].y,12,0,Math.PI*2);ctx.stroke()}}
    }
    ctx.restore();
  };

  function nearestControl(p){let best=-1,dist=16;state.points.forEach((q,i)=>{const d=Math.hypot(q.x-p.x,q.y-p.y);if(d<dist){dist=d;best=i}});return best}
  function nearestT(p){const samples=sampleTrack(500);let best=0,dist=Infinity;samples.forEach((q,i)=>{const d=(q.x-p.x)**2+(q.y-p.y)**2;if(d<dist){dist=d;best=i}});return best/samples.length}
  function setMode(next){mode=next;document.querySelectorAll('.tool[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));ui.drawHint.classList.toggle('hidden',mode!=='draw');canvas.style.cursor=mode==='edit'?'default':'crosshair';draw()}
  function updateUI(){ui.trackName.value=state.name;ui.width.value=state.width;ui.widthValue.value=state.width;ui.numberToggle.checked=state.showNumbers;ui.lineToggle.checked=state.showLine;document.querySelectorAll('.swatch').forEach(b=>b.classList.toggle('active',b.dataset.palette===state.palette));const samples=sampleTrack(250),distance=samples.reduce((sum,p,i)=>sum+(i?Math.hypot(p.x-samples[i-1].x,p.y-samples[i-1].y):0),0);ui.length.textContent=Math.max(.1,distance/160).toFixed(2);ui.turns.textContent=state.points.length;ui.undo.disabled=!history.length;ui.redo.disabled=!future.length;ui.width.style.background=`linear-gradient(90deg,var(--acid) ${(state.width-16)/16*100}%,#343941 0%)`;draw()}

  updateUI=function(){ui.trackName.value=state.name;ui.width.value=state.width;ui.widthValue.value=state.width;ui.numberToggle.checked=state.showNumbers;ui.autoConnectToggle.checked=state.autoConnect;ui.lineToggle.checked=state.showLine;document.querySelectorAll('.swatch').forEach(b=>b.classList.toggle('active',b.dataset.palette===state.palette));const samples=sampleTrack(250),distance=samples.reduce((sum,p,i)=>sum+(i?Math.hypot(p.x-samples[i-1].x,p.y-samples[i-1].y):0),0);ui.length.textContent=Math.max(.1,distance/160).toFixed(2);ui.turns.textContent=state.points.length;ui.undo.disabled=!history.length;ui.redo.disabled=!future.length;ui.width.style.background=`linear-gradient(90deg,var(--acid) ${(state.width-16)/16*100}%,#343941 0%)`;draw()};

  updateUI=function(){ui.trackName.value=state.name;ui.profileName.value=state.name;ui.profileCode.value=state.profile.code;ui.profileCountry.value=state.profile.country;ui.profileLocation.value=state.profile.location;ui.profileDirection.value=state.profile.direction;ui.profileCodeDisplay.textContent=state.profile.code||'---';ui.profileCountryDisplay.textContent=state.profile.country||'---';ui.width.value=state.width;ui.widthValue.value=state.width;ui.numberToggle.checked=state.showNumbers;ui.autoConnectToggle.checked=state.autoConnect;ui.lineToggle.checked=state.showLine;document.querySelectorAll('.swatch').forEach(b=>b.classList.toggle('active',b.dataset.palette===state.palette));const samples=sampleTrack(250),distance=samples.reduce((sum,p,i)=>sum+(i?Math.hypot(p.x-samples[i-1].x,p.y-samples[i-1].y):0),0);ui.length.textContent=Math.max(.1,distance/160).toFixed(2);ui.turns.textContent=state.points.length;ui.undo.disabled=!history.length;ui.redo.disabled=!future.length;ui.width.style.background=`linear-gradient(90deg,var(--acid) ${(state.width-16)/16*100}%,#343941 0%)`;draw()};

  canvas.addEventListener('pointerdown',e=>{const p=toWorld(e);if(mode==='draw'&&state.autoConnect&&state.points.length>=3&&Math.hypot(p.x-state.points[0].x,p.y-state.points[0].y)<20){e.stopImmediatePropagation();const old=clone(state);state.closed=true;commit(old);setMode('edit');notify('Start and finish connected automatically')}},true);
  canvas.addEventListener('pointerdown',e=>{const p=toWorld(e);pointer=p;if(mode==='edit'){const i=nearestControl(p);if(i>=0){dragging=i;canvas.setPointerCapture(e.pointerId);history.push(clone(state));future=[]}}else if(mode==='draw'){if(state.closed){history.push(clone(state));future=[];state.points=[];state.markers=[];state.closed=false}state.points.push(p);save();updateUI()}else if((mode==='drs'||mode==='trap')&&state.closed&&state.points.length>2){const old=clone(state),type=mode==='drs'?'drs':'trap',count=state.markers.filter(m=>m.type===type).length+1;state.markers.push({type,t:nearestT(p),label:type==='drs'?`DRS\nZONE ${count}`:'SPEED\nTRAP'});commit(old);notify(type==='drs'?'DRS zone placed':'Speed trap placed')}});
  canvas.addEventListener('pointermove',e=>{pointer=toWorld(e);if(dragging>=0){state.points[dragging]=pointer;draw()}else if(mode==='edit'){hoverPoint=nearestControl(pointer);canvas.style.cursor=hoverPoint>=0?'grab':'default';draw()}else if(mode==='draw')draw()});
  canvas.addEventListener('pointerup',e=>{if(dragging>=0){dragging=-1;save();updateUI();try{canvas.releasePointerCapture(e.pointerId)}catch{}}});
  canvas.addEventListener('dblclick',e=>{if(mode==='draw'&&state.points.length>=3){e.preventDefault();state.points.pop();state.closed=state.autoConnect;save();updateUI();setMode('edit');notify(state.closed?'Circuit auto-connected — ready to race':'Open track finished with three sectors')}});
  document.querySelectorAll('.tool[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));
  document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{const old=clone(state);state.points=presets[b.dataset.preset].map(([x,y])=>({x,y}));state.closed=true;state.markers=[];commit(old);setMode('edit');notify(`${b.dataset.preset.toUpperCase()} preset loaded`)}));
  document.querySelectorAll('.swatch').forEach(b=>b.addEventListener('click',()=>{const old=clone(state);state.palette=b.dataset.palette;commit(old)}));
  ui.width.addEventListener('input',()=>{state.width=+ui.width.value;ui.widthValue.value=state.width;ui.width.style.background=`linear-gradient(90deg,var(--acid) ${(state.width-16)/16*100}%,#343941 0%)`;draw()});ui.width.addEventListener('change',save);
  ui.numberToggle.addEventListener('change',()=>{state.showNumbers=ui.numberToggle.checked;save();draw()});ui.autoConnectToggle.addEventListener('change',()=>{state.autoConnect=ui.autoConnectToggle.checked;save();draw();notify(state.autoConnect?'Auto-connect enabled':'Auto-connect disabled')});ui.lineToggle.addEventListener('change',()=>{state.showLine=ui.lineToggle.checked;save();draw()});ui.trackName.addEventListener('input',()=>{state.name=ui.trackName.value.toUpperCase();save()});
  ui.trackName.addEventListener('input',()=>{ui.profileName.value=state.name});
  ui.profileName.addEventListener('input',()=>{state.name=ui.profileName.value.toUpperCase();ui.profileName.value=state.name;ui.trackName.value=state.name;save()});
  ui.profileCode.addEventListener('input',()=>{state.profile.code=ui.profileCode.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,3);ui.profileCode.value=state.profile.code;ui.profileCodeDisplay.textContent=state.profile.code||'---';save()});
  ui.profileCountry.addEventListener('input',()=>{state.profile.country=ui.profileCountry.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,3);ui.profileCountry.value=state.profile.country;ui.profileCountryDisplay.textContent=state.profile.country||'---';save()});
  ui.profileLocation.addEventListener('input',()=>{state.profile.location=ui.profileLocation.value.toUpperCase();ui.profileLocation.value=state.profile.location;save()});
  ui.profileDirection.addEventListener('change',()=>{state.profile.direction=ui.profileDirection.value;save();notify(`${ui.profileDirection.options[ui.profileDirection.selectedIndex].text} layout`) });
  document.getElementById('gridBtn').addEventListener('click',e=>{e.currentTarget.classList.toggle('active');draw()});document.getElementById('fitBtn').addEventListener('click',()=>notify('Track fitted to canvas'));
  document.getElementById('resetBtn').addEventListener('click',()=>{const old=clone(state);state=defaultState();commit(old);setMode('edit');notify('Demo circuit restored')});
  document.getElementById('newBtn').addEventListener('click',()=>{const old=clone(state);state.points=[];state.markers=[];state.closed=false;commit(old);setMode('draw');notify('Click the canvas to begin')});
  function undo(){if(!history.length)return;future.push(clone(state));state=history.pop();save();updateUI()}function redo(){if(!future.length)return;history.push(clone(state));state=future.pop();save();updateUI()}
  ui.undo.addEventListener('click',undo);ui.redo.addEventListener('click',redo);
  window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}if(e.key==='Escape')setMode('edit');if((e.key==='Delete'||e.key==='Backspace')&&hoverPoint>=0&&document.activeElement!==ui.trackName){const old=clone(state);state.points.splice(hoverPoint,1);hoverPoint=-1;commit(old)}});
  document.getElementById('exportBtn').addEventListener('click',()=>{const link=document.createElement('a');link.download=`${state.name.toLowerCase().replace(/[^a-z0-9]+/g,'-')||'apex-track'}.png`;link.href=canvas.toDataURL('image/png');link.click();notify('PNG exported')});
  window.addEventListener('resize',resize);updateUI();resize();
})();
