(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const canvas = $('trackCanvas'), frame = $('canvasFrame'), ctx = canvas.getContext('2d');
  const ui = {
    trackName:$('trackName'), profileName:$('profileName'), profileCode:$('profileCode'), profileCountry:$('profileCountry'),
    profileLocation:$('profileLocation'), profileDirection:$('profileDirection'), profileCodeDisplay:$('profileCodeDisplay'),
    profileCountryDisplay:$('profileCountryDisplay'), length:$('lengthValue'), turns:$('turnValue'), width:$('trackWidth'),
    widthValue:$('widthValue'), edgeWidth:$('edgeWidth'), edgeWidthValue:$('edgeWidthValue'), racingWidth:$('racingWidth'),
    racingWidthValue:$('racingWidthValue'), numberToggle:$('numberToggle'), autoConnectToggle:$('autoConnectToggle'),
    lineToggle:$('lineToggle'), curbToggle:$('curbToggle'), sector2Range:$('sector2Range'), sector3Range:$('sector3Range'), sector2Value:$('sector2Value'),
    sector3Value:$('sector3Value'), markerEditor:$('markerEditor'), markerType:$('markerType'), markerLabel:$('markerLabel'),
    markerPosition:$('markerPosition'), markerPositionValue:$('markerPositionValue'), drawHint:$('drawHint'), toast:$('toast'),
    driveHud:$('driveHud'), driveSpeed:$('driveSpeed'), driveLap:$('driveLap'), driveTime:$('driveTime'),
    driveTool:$('driveTool'), startDrive:$('startDriveBtn'), deleteCorner:$('deleteCornerBtn'), cornerSelection:$('cornerSelection'), saveState:$('saveState'), undo:$('undoBtn'), redo:$('redoBtn'), grid:$('gridBtn')
  };
  const palettes={classic:['#ffe000','#ff3045','#19c7f5'],sunset:['#ffb000','#ff5e76','#9b5cff'],mono:['#b6bac0','#68707a','#20252b']};
  const technicalTrack=[[205,140],[318,105],[430,120],[535,175],[610,145],[690,190],[670,275],[735,315],[700,400],[600,435],[545,395],[465,455],[375,430],[330,365],[250,380],[165,325],[130,245]];

  function defaultState(){return{name:'ORBITAL GRAND PRIX',profile:{code:'ORB',country:'IRN',location:'TEHRAN, IRAN',direction:'clockwise'},points:technicalTrack.map(([x,y])=>({x,y})),markers:[{type:'drs',t:.10,label:'DRS\nZONE 1'},{type:'drs',t:.56,label:'DRS\nZONE 2'},{type:'trap',t:.78,label:'SPEED\nTRAP'}],sectors:[0,.334,.667],width:22,edgeWidth:10,racingWidth:4,palette:'classic',showNumbers:true,autoConnect:true,showLine:true,showKerbs:true,showGrid:true,closed:true}}
  const clone=value=>JSON.parse(JSON.stringify(value));
  function loadState(){try{return JSON.parse(localStorage.getItem('apex-track-state'))}catch{return null}}
  function normalizeState(value){const base=defaultState(),next={...base,...(value||{})};next.profile={...base.profile,...((value||{}).profile||{})};if(!Array.isArray(next.points))next.points=base.points;if(!Array.isArray(next.markers))next.markers=[];if(!Array.isArray(next.sectors)||next.sectors.length!==3)next.sectors=base.sectors;return next}
  let state=normalizeState(loadState()),mode='edit',history=[],future=[],draggingPoint=-1,hoverPoint=-1,selectedCorner=-1,selectedMarker=-1,markerDragging=false,pointer={x:0,y:0},toastTimer,saveTimer;
  const drive={active:false,view:'driver',progress:0,speed:0,lateral:0,steer:0,braking:false,lap:1,elapsed:0,lastLap:0,lastFrame:0,keys:new Set(),animation:0};

  function save(){clearTimeout(saveTimer);ui.saveState.classList.add('saving');ui.saveState.lastChild.textContent=' SAVING';localStorage.setItem('apex-track-state',JSON.stringify(state));saveTimer=setTimeout(()=>{ui.saveState.classList.remove('saving');ui.saveState.lastChild.textContent=' SAVED'},320)}
  function commit(previous){if(previous)history.push(previous);if(history.length>60)history.shift();future=[];save();updateUI()}
  function notify(message){clearTimeout(toastTimer);ui.toast.textContent=message;ui.toast.classList.add('show');toastTimer=setTimeout(()=>ui.toast.classList.remove('show'),1900)}
  function view(){const width=frame.clientWidth,height=frame.clientHeight,scale=Math.min(width/900,height/560);return{scale,ox:(width-900*scale)/2,oy:(height-560*scale)/2}}
  function resize(){const rect=frame.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.floor(rect.width*dpr));canvas.height=Math.max(1,Math.floor(rect.height*dpr));canvas.style.width=`${rect.width}px`;canvas.style.height=`${rect.height}px`;ctx.setTransform(dpr,0,0,dpr,0,0);draw()}
  function toWorld(event){const rect=canvas.getBoundingClientRect(),v=view();return{x:(event.clientX-rect.left-v.ox)/v.scale,y:(event.clientY-rect.top-v.oy)/v.scale}}

  // Road and racing line use these exact same Bezier samples, preventing drift on tight bends.
  function sampleTrack(targetSamples=480){
    const points=state.points;if(points.length<2)return points.map(point=>({...point}));
    const count=points.length,segments=state.closed?count:count-1,steps=Math.max(8,Math.ceil(targetSamples/segments)),tension=.72;
    const get=index=>state.closed?points[(index+count)%count]:points[Math.max(0,Math.min(count-1,index))],samples=[];
    for(let segment=0;segment<segments;segment++){
      const p0=get(segment-1),p1=get(segment),p2=get(segment+1),p3=get(segment+2);
      const c1={x:p1.x+(p2.x-p0.x)*tension/6,y:p1.y+(p2.y-p0.y)*tension/6};
      const c2={x:p2.x-(p3.x-p1.x)*tension/6,y:p2.y-(p3.y-p1.y)*tension/6};
      for(let step=0;step<steps;step++){
        const t=step/steps,mt=1-t,mt2=mt*mt,t2=t*t;
        samples.push({x:mt2*mt*p1.x+3*mt2*t*c1.x+3*mt*t2*c2.x+t2*t*p2.x,y:mt2*mt*p1.y+3*mt2*t*c1.y+3*mt*t2*c2.y+t2*t*p2.y});
      }
    }
    if(!state.closed)samples.push({...points[count-1]});return samples;
  }
  function pathFromSamples(samples){const path=new Path2D();if(!samples.length)return path;path.moveTo(samples[0].x,samples[0].y);for(let i=1;i<samples.length;i++)path.lineTo(samples[i].x,samples[i].y);if(state.closed)path.closePath();return path}
  function pointOnTrack(t,samples){const max=state.closed?samples.length:samples.length-1;return samples[Math.min(samples.length-1,Math.floor(Math.max(0,Math.min(1,t))*max))]}
  function nearestTrack(point,count=800){const samples=sampleTrack(count);let index=0,distance=Infinity;samples.forEach((sample,i)=>{const value=Math.hypot(sample.x-point.x,sample.y-point.y);if(value<distance){distance=value;index=i}});return{t:index/Math.max(1,state.closed?samples.length:samples.length-1),distance,point:samples[index]}}

  function drawGrid(width,height){if(!state.showGrid)return;ctx.save();ctx.strokeStyle='#e7e7e3';ctx.lineWidth=1;for(let x=0;x<width;x+=32){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,height);ctx.stroke()}for(let y=0;y<height;y+=32){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(width,y);ctx.stroke()}ctx.restore()}
  function strokeSector(samples,start,end,color){if(samples.length<2)return;const max=state.closed?samples.length:samples.length-1,first=Math.floor(start*max),last=Math.floor(end*max),path=new Path2D(),startPoint=samples[first%samples.length];path.moveTo(startPoint.x,startPoint.y);for(let i=first+1;i<=last;i++){const point=samples[state.closed?i%samples.length:Math.min(i,samples.length-1)];path.lineTo(point.x,point.y)}ctx.save();ctx.strokeStyle=color;ctx.lineWidth=Math.min(state.racingWidth,Math.max(2,state.width-8));ctx.lineCap='butt';ctx.lineJoin='round';ctx.stroke(path);ctx.restore()}
  function drawSectorDivisions(samples){if(samples.length<8)return;const colors=palettes[state.palette]||palettes.classic;state.sectors.slice(1).forEach((t,sectorIndex)=>{const max=state.closed?samples.length:samples.length-1,index=Math.min(samples.length-1,Math.floor(t*max)),point=samples[index],before=samples[state.closed?(index-3+samples.length)%samples.length:Math.max(0,index-3)],after=samples[state.closed?(index+3)%samples.length:Math.min(samples.length-1,index+3)],angle=Math.atan2(after.y-before.y,after.x-before.x),nx=Math.cos(angle+Math.PI/2),ny=Math.sin(angle+Math.PI/2),half=Math.max(2,state.width/2-Math.max(3,state.racingWidth/2+1));ctx.save();ctx.strokeStyle='#111318';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(point.x-nx*half,point.y-ny*half);ctx.lineTo(point.x+nx*half,point.y+ny*half);ctx.stroke();if(mode==='sector'){ctx.fillStyle='#f8f8f6';ctx.beginPath();ctx.arc(point.x,point.y,8,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#111318';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle=colors[sectorIndex+1];ctx.beginPath();ctx.arc(point.x,point.y,4,0,Math.PI*2);ctx.fill()}ctx.restore()})}
  function angleDelta(a,b){let value=a-b;while(value>Math.PI)value-=Math.PI*2;while(value<-Math.PI)value+=Math.PI*2;return value}
  function drawMapKerbs(samples){if(!state.showKerbs||samples.length<24)return;const block=4,limit=state.width/2-3;for(let i=7;i<samples.length-8;i+=block){const previous=samples[i-6],point=samples[i],next=samples[i+6],headingIn=Math.atan2(point.y-previous.y,point.x-previous.x),headingOut=Math.atan2(next.y-point.y,next.x-point.x),bend=angleDelta(headingOut,headingIn);if(Math.abs(bend)<.052)continue;const side=bend>0?-1:1,nx=Math.cos(headingIn+Math.PI/2)*side,ny=Math.sin(headingIn+Math.PI/2)*side,a=samples[i],b=samples[Math.min(samples.length-1,i+block)];ctx.save();ctx.lineCap='butt';ctx.lineJoin='round';ctx.strokeStyle='#16191d';ctx.lineWidth=5.2;ctx.beginPath();ctx.moveTo(a.x+nx*limit,a.y+ny*limit);ctx.lineTo(b.x+nx*limit,b.y+ny*limit);ctx.stroke();ctx.strokeStyle=Math.floor(i/block)%2?'#f4f2ec':'#e3263d';ctx.lineWidth=3.25;ctx.beginPath();ctx.moveTo(a.x+nx*limit,a.y+ny*limit);ctx.lineTo(b.x+nx*limit,b.y+ny*limit);ctx.stroke();ctx.strokeStyle='rgba(255,255,255,.38)';ctx.lineWidth=.55;ctx.beginPath();ctx.moveTo(a.x+nx*(limit-1),a.y+ny*(limit-1));ctx.lineTo(b.x+nx*(limit-1),b.y+ny*(limit-1));ctx.stroke();ctx.restore()}}
  function drawStartFinish(samples){if(samples.length<5)return;drawMapKerbs(samples);const point=samples[0],next=samples[4],angle=Math.atan2(next.y-point.y,next.x-point.x),size=4;ctx.save();ctx.translate(point.x,point.y);ctx.rotate(angle);for(let row=0;row<2;row++)for(let col=0;col<5;col++){ctx.fillStyle=(row+col)%2?'#fff':'#111318';ctx.fillRect(-size*2.5+col*size,-state.width/2+2+row*size,size,size)}ctx.restore()}
  function drawMarker(marker,samples,index){const point=pointOnTrack(marker.t,samples),isDrs=marker.type==='drs',color=isDrs?'#20c52b':'#ed00de',side=point.x<450?-1:1,boxWidth=isDrs?108:86,boxHeight=43;let boxX=point.x+side*45-(side<0?boxWidth:0),boxY=point.y+(point.y<260?52:-78);boxX=Math.max(12,Math.min(888-boxWidth,boxX));boxY=Math.max(12,Math.min(548-boxHeight,boxY));ctx.save();ctx.strokeStyle=color;ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(point.x,point.y);ctx.lineTo(point.x,boxY+boxHeight/2);ctx.lineTo(side<0?boxX+boxWidth:boxX,boxY+boxHeight/2);ctx.stroke();if(index===selectedMarker){ctx.setLineDash([3,2]);ctx.strokeStyle='#111318';ctx.lineWidth=2;ctx.beginPath();ctx.arc(point.x,point.y,11,0,Math.PI*2);ctx.stroke();ctx.setLineDash([])}ctx.fillStyle=color;ctx.beginPath();ctx.arc(point.x,point.y,6,0,Math.PI*2);ctx.fill();ctx.fillRect(boxX,boxY,boxWidth,boxHeight);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='800 12px Manrope,Arial';marker.label.split('\n').slice(0,2).forEach((line,lineIndex)=>ctx.fillText(line,boxX+boxWidth/2,boxY+15+lineIndex*13,boxWidth-10));ctx.restore()}
  function cornerBadgePositions(){const points=state.points;if(!points.length)return[];const center=points.reduce((sum,point)=>({x:sum.x+point.x/points.length,y:sum.y+point.y/points.length}),{x:0,y:0}),placed=[];return points.map((point,index)=>{const previous=points[state.closed?(index-1+points.length)%points.length:Math.max(0,index-1)],next=points[state.closed?(index+1)%points.length:Math.min(points.length-1,index+1)];let nx=-(next.y-previous.y),ny=next.x-previous.x,length=Math.hypot(nx,ny)||1;nx/=length;ny/=length;if(nx*(point.x-center.x)+ny*(point.y-center.y)<0){nx*=-1;ny*=-1}let distance=state.width+8,candidate={x:point.x+nx*distance,y:point.y+ny*distance};for(let attempt=0;attempt<3&&placed.some(item=>Math.hypot(item.x-candidate.x,item.y-candidate.y)<25);attempt++){distance+=15;candidate={x:point.x+nx*distance,y:point.y+ny*distance}}placed.push(candidate);return candidate})}
  function drawCornerNumbers(){cornerBadgePositions().forEach((position,index)=>{ctx.fillStyle='#111318';ctx.beginPath();ctx.arc(position.x,position.y,11,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=1;ctx.stroke();ctx.fillStyle='#fff';ctx.font='800 8px Manrope,Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(index+1).padStart(2,'0'),position.x,position.y+.5)})}

  function drawDriverView(width,height){
    const speedRatio=drive.speed/335,flow=drive.elapsed*(1.8+speedRatio*8),horizon=height*(.31+Math.sin(flow*1.9)*speedRatio*.004),bottom=height*1.045,roll=drive.steer*speedRatio*width*.022,bob=Math.sin(flow*4.1)*speedRatio*2,fov=.94+speedRatio*.16;
    const sky=ctx.createLinearGradient(0,0,0,horizon+55);sky.addColorStop(0,'#1e527d');sky.addColorStop(.48,'#75b5d7');sky.addColorStop(.78,'#d6e7e4');sky.addColorStop(1,'#f2cc9d');ctx.fillStyle=sky;ctx.fillRect(0,0,width,height);
    const sunX=width*(.77-roll/width*.8),sun=ctx.createRadialGradient(sunX,horizon*.2,2,sunX,horizon*.2,width*.23);sun.addColorStop(0,'rgba(255,253,216,.92)');sun.addColorStop(.12,'rgba(255,241,184,.52)');sun.addColorStop(.54,'rgba(255,222,163,.10)');sun.addColorStop(1,'rgba(255,222,163,0)');ctx.fillStyle=sun;ctx.fillRect(0,0,width,horizon*1.9);
    ctx.save();ctx.globalAlpha=.18;ctx.fillStyle='#fff';for(let i=0;i<5;i++){const x=(i*229+flow*7)%width;ctx.beginPath();ctx.ellipse(x,horizon*.28+(i%2)*11,58,5,0,0,Math.PI*2);ctx.fill()}ctx.restore();
    ctx.fillStyle='#355838';ctx.fillRect(0,horizon,width,height-horizon);ctx.fillStyle='#75805d';ctx.beginPath();ctx.moveTo(0,horizon+23);for(let x=0;x<=width+64;x+=64)ctx.lineTo(x,horizon-5-Math.sin(x*.019+flow*.04)*15-Math.sin(x*.057)*7);ctx.lineTo(width,horizon+28);ctx.closePath();ctx.fill();
    ctx.fillStyle='#263f2d';for(let x=-12;x<width+24;x+=38){const treeHeight=10+((x*19)%19);ctx.fillRect(x-roll*.16,horizon-treeHeight,4,treeHeight);ctx.beginPath();ctx.arc(x-roll*.16,horizon-treeHeight,7+(x%5),0,Math.PI*2);ctx.fill()}ctx.save();ctx.globalAlpha=.2;ctx.fillStyle='#1e482c';for(let i=0;i<52;i++){const x=(i*71+flow*19)%width,y=horizon+24+(i*37%(height-horizon));ctx.fillRect(x,y,2+(i%4),1)}ctx.restore();
    ctx.fillStyle='#d2d9dc';for(let x=width*.05;x<width*.32;x+=9){const grandstandHeight=11+((x*11)%14);ctx.fillRect(x-roll*.08,horizon-grandstandHeight,7,grandstandHeight);ctx.fillStyle='#4c5c65';ctx.fillRect(x-roll*.08,horizon-grandstandHeight-2,7,2);ctx.fillStyle='#d2d9dc'}
    const samples=sampleTrack(1320),count=samples.length,direction=state.profile.direction==='counterclockwise'?-1:1,currentIndex=Math.floor(drive.progress*count)%count,current=samples[currentIndex],before=samples[(currentIndex-direction*3+count)%count],after=samples[(currentIndex+direction*3+count)%count],currentHeading=Math.atan2(after.y-before.y,after.x-before.x),normalX=-Math.sin(currentHeading),normalY=Math.cos(currentHeading),slices=72,lookahead=Math.min(Math.floor(count*.2),260),road=[];
    for(let slice=0;slice<=slices;slice++){const depth=slice/slices,offset=Math.max(1,Math.floor(Math.pow(depth,1.16)*lookahead)),index=(currentIndex+direction*offset+count*2)%count,point=samples[index],pBefore=samples[(index-direction*2+count)%count],pAfter=samples[(index+direction*2+count)%count],heading=Math.atan2(pAfter.y-pBefore.y,pAfter.x-pBefore.x),curve=angleDelta(heading,currentHeading),relativeX=(point.x-current.x)*normalX+(point.y-current.y)*normalY,bend=Math.sin(curve)*width*.15,driverShift=-(drive.lateral/Math.max(8,state.width))*width*.47*(1-depth),center=width/2+roll+Math.tanh(relativeX/96)*width*.31+bend-driverShift,y=bottom-Math.pow(depth,.565)*(bottom-horizon)+bob*(1-depth),half=(5+Math.pow(1-depth,1.68)*width*.425)*fov;road.push({center,y,half,index,depth,curve})}
    const roadTone=ctx.createLinearGradient(0,horizon,0,bottom);roadTone.addColorStop(0,'#5a6061');roadTone.addColorStop(.32,'#3c4244');roadTone.addColorStop(1,'#121519');ctx.fillStyle=roadTone;ctx.beginPath();road.forEach((point,index)=>index?ctx.lineTo(point.center-point.half,point.y):ctx.moveTo(point.center-point.half,point.y));for(let i=road.length-1;i>=0;i--)ctx.lineTo(road[i].center+road[i].half,road[i].y);ctx.closePath();ctx.fill();
    ctx.save();ctx.globalAlpha=.15;ctx.strokeStyle='#b9c0bd';ctx.lineWidth=1;for(let i=5;i<road.length;i+=5){const point=road[i],grain=(Math.sin(i*17+flow*9)+1)*.5;ctx.beginPath();ctx.moveTo(point.center-point.half*.72,point.y);ctx.lineTo(point.center+point.half*(grain-.1),point.y);ctx.stroke()}ctx.restore();
    for(let i=road.length-2;i>=0;i--){const near=road[i],far=road[i+1],side=near.curve>=0?-1:1,edgeNear=near.center+side*near.half,edgeFar=far.center+side*far.half,bandNear=Math.max(2,near.half*.115),bandFar=Math.max(1,far.half*.115),hasCurb=state.showKerbs&&(Math.abs(near.curve)>.022||i<9),redWhite=Math.floor((i+flow*.78)/3)%2===0,paint=redWhite?'#ef3045':'#f7f4ea',shade=redWhite?'#a81b2e':'#c9c7bf';ctx.fillStyle='#090c10';ctx.beginPath();ctx.moveTo(edgeNear+side*1.5,near.y);ctx.lineTo(edgeFar+side*1.5,far.y);ctx.lineTo(edgeFar-side*bandFar,far.y);ctx.lineTo(edgeNear-side*bandNear,near.y);ctx.closePath();ctx.fill();if(hasCurb){ctx.fillStyle=paint;ctx.beginPath();ctx.moveTo(edgeNear-side*1.2,near.y);ctx.lineTo(edgeFar-side*1.2,far.y);ctx.lineTo(edgeFar-side*bandFar*.8,far.y);ctx.lineTo(edgeNear-side*bandNear*.8,near.y);ctx.closePath();ctx.fill();ctx.fillStyle=shade;ctx.beginPath();ctx.moveTo(edgeNear-side*bandNear*.8,near.y);ctx.lineTo(edgeFar-side*bandFar*.8,far.y);ctx.lineTo(edgeFar-side*bandFar,far.y);ctx.lineTo(edgeNear-side*bandNear,near.y);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(255,255,255,.48)';ctx.lineWidth=Math.max(.4,near.half*.004);ctx.beginPath();ctx.moveTo(edgeNear-side*1.5,near.y);ctx.lineTo(edgeFar-side*1.5,far.y);ctx.stroke();ctx.strokeStyle='rgba(12,15,18,.58)';ctx.lineWidth=Math.max(.5,near.half*.009);ctx.beginPath();ctx.moveTo(edgeNear-side*bandNear*.76,near.y);ctx.lineTo(edgeFar-side*bandFar*.76,far.y);ctx.stroke()}else{ctx.strokeStyle='#e8e9e4';ctx.lineWidth=Math.max(1,near.half*.02);ctx.beginPath();ctx.moveTo(edgeNear-side*bandNear*.15,near.y);ctx.lineTo(edgeFar-side*bandFar*.15,far.y);ctx.stroke()}}
    for(let i=12;i<road.length-3;i+=12){const point=road[i],side=Math.floor(i/12)%2?-1:1,size=Math.max(3,point.half*.085),x=point.center+side*(point.half+size*2.1),y=point.y-size*2.4;ctx.save();ctx.fillStyle='#f4f5f2';ctx.fillRect(x-size,y,size*2,size*2.45);ctx.fillStyle='#15191e';ctx.font=`800 ${Math.max(4,size*.9)}px "DM Mono",monospace`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(Math.max(50,Math.round((i/12)*50))),x,y+size*1.25);ctx.restore()}
    const colors=palettes[state.palette]||palettes.classic;for(let i=road.length-2;i>=0;i--){const near=road[i],far=road[i+1],trackT=near.index/count,color=trackT<state.sectors[1]?colors[0]:trackT<state.sectors[2]?colors[1]:colors[2];ctx.strokeStyle=color;ctx.globalAlpha=.9;ctx.lineWidth=1+(1-near.depth)*state.racingWidth;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(near.center,near.y);ctx.lineTo(far.center,far.y);ctx.stroke()}ctx.globalAlpha=1;
    ctx.strokeStyle='#ffffff18';ctx.lineWidth=1;for(let i=8;i<road.length;i+=7){ctx.beginPath();ctx.moveTo(road[i].center-road[i].half,road[i].y);ctx.lineTo(road[i].center+road[i].half,road[i].y);ctx.stroke()}
    if(drive.speed>115){ctx.strokeStyle=`rgba(231,246,255,${Math.min(.28,(drive.speed-115)/520)})`;ctx.lineWidth=1;for(let i=0;i<30;i++){const x=(i*71+31+flow*43)%width,y=(i*53+flow*220)%height,len=9+(i%6)*8;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+(x-width/2)*.032,y+len);ctx.stroke()}}ctx.save();ctx.globalAlpha=.09+speedRatio*.09;ctx.strokeStyle='#dff7ff';ctx.lineWidth=1;for(let i=0;i<5;i++){const y=horizon+12+i*6+Math.sin(flow*6+i)*2;ctx.beginPath();ctx.moveTo(width*.27,y);ctx.lineTo(width*.73,y);ctx.stroke()}ctx.restore();
    const cockpit=ctx.createLinearGradient(0,height*.63,0,height);cockpit.addColorStop(0,'#10141900');cockpit.addColorStop(.2,'#1c2229');cockpit.addColorStop(1,'#040609');ctx.fillStyle=cockpit;ctx.beginPath();ctx.moveTo(0,height*.68);ctx.quadraticCurveTo(width*.18,height*.75,width*.34,height);ctx.lineTo(width*.66,height);ctx.quadraticCurveTo(width*.82,height*.75,width,height*.68);ctx.lineTo(width,height);ctx.lineTo(0,height);ctx.closePath();ctx.fill();ctx.save();ctx.strokeStyle='rgba(255,255,255,.05)';ctx.lineWidth=1;for(let x=-width*.2;x<width;x+=13){ctx.beginPath();ctx.moveTo(x,height*.78);ctx.lineTo(x+width*.18,height);ctx.stroke()}ctx.restore();
    ctx.fillStyle=drive.braking?'#f13b4e':'#c9f02f';ctx.beginPath();ctx.moveTo(width*.45,height);ctx.lineTo(width*.48,height*.6);ctx.lineTo(width*.52,height*.6);ctx.lineTo(width*.55,height);ctx.closePath();ctx.fill();ctx.fillStyle='#12161b';ctx.fillRect(width*.486,height*.605,width*.028,height*.15);ctx.fillStyle=drive.braking?'#ff4052':'#e7384a';ctx.fillRect(width*.493,height*.62,width*.014,height*.055);
    ctx.strokeStyle='#080b0f';ctx.lineWidth=Math.max(12,width*.013);ctx.lineCap='round';ctx.beginPath();ctx.moveTo(width*.5,height*.8);ctx.lineTo(width*.5,height*.395);ctx.moveTo(width*.5,height*.43);ctx.quadraticCurveTo(width*.265,height*.45,width*.13,height*.7);ctx.moveTo(width*.5,height*.43);ctx.quadraticCurveTo(width*.735,height*.45,width*.87,height*.7);ctx.stroke();ctx.strokeStyle='#4b535c';ctx.lineWidth=1.2;ctx.stroke();
    for(const side of [-1,1]){ctx.save();ctx.translate(width*.5+side*width*.255,height*.72);ctx.rotate(side*.18);ctx.fillStyle='#080b0e';ctx.strokeStyle='#69737c';ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(-width*.045,-height*.022,width*.09,height*.044,5);ctx.fill();ctx.stroke();const mirror=ctx.createLinearGradient(0,-height*.022,0,height*.022);mirror.addColorStop(0,'#91c5d8');mirror.addColorStop(1,'#1b3542');ctx.fillStyle=mirror;ctx.beginPath();ctx.roundRect(-width*.034,-height*.014,width*.068,height*.027,3);ctx.fill();ctx.restore()}
    const gear=Math.min(8,1+Math.floor(drive.speed/47)),guide=road[Math.min(road.length-1,38)],turnLabel=guide.curve>.05?'LEFT':guide.curve<-.05?'RIGHT':'STRAIGHT';ctx.save();ctx.translate(width*.5+drive.steer*width*.012,height*.835);ctx.rotate(drive.steer*.18);ctx.fillStyle='#090c10';ctx.strokeStyle='#5b6570';ctx.lineWidth=5;ctx.beginPath();ctx.ellipse(0,0,width*.126,height*.082,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#212830';ctx.fillRect(-width*.086,-height*.044,width*.172,height*.088);ctx.fillStyle='#07090c';ctx.fillRect(-width*.059,-height*.032,width*.118,height*.045);ctx.fillStyle=drive.braking?'#ff5564':'#d8ff38';ctx.font=`700 ${Math.max(10,width*.013)}px "DM Mono",monospace`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(`${gear}  ${String(Math.round(drive.speed)).padStart(3,'0')}`,0,-height*.01);ctx.font=`600 ${Math.max(5,width*.0055)}px "DM Mono",monospace`;ctx.fillStyle='#d6dde1';ctx.fillText(drive.braking?'BRAKE':turnLabel,0,height*.026);for(let i=0;i<12;i++){ctx.fillStyle=i<Math.ceil(speedRatio*12)?(i>8?'#ff3b4e':'#d8ff38'):'#313841';ctx.fillRect(-width*.065+i*width*.011,height*.019,width*.0075,height*.008)}ctx.fillStyle='#e9edef';ctx.beginPath();ctx.ellipse(-width*.15,0,width*.047,height*.031,-.18,0,Math.PI*2);ctx.ellipse(width*.15,0,width*.047,height*.031,.18,0,Math.PI*2);ctx.fill();ctx.fillStyle='#20272e';ctx.fillRect(-width*.164,-height*.009,width*.027,height*.018);ctx.fillRect(width*.137,-height*.009,width*.027,height*.018);ctx.fillStyle=drive.braking?'#ff3b4e':'#d8ff38';ctx.beginPath();ctx.arc(-width*.099,height*.019,width*.008,0,Math.PI*2);ctx.arc(width*.099,height*.019,width*.008,0,Math.PI*2);ctx.fill();ctx.restore();
  }

  function drawDriveCar(samples){
    if(!drive.active||samples.length<6)return;
    const count=samples.length,index=Math.floor(drive.progress*count)%count,direction=state.profile.direction==='counterclockwise'?-1:1;
    const point=samples[index],before=samples[(index-direction*3+count)%count],after=samples[(index+direction*3+count)%count];
    const angle=Math.atan2(after.y-before.y,after.x-before.x),nx=Math.cos(angle+Math.PI/2),ny=Math.sin(angle+Math.PI/2);
    const x=point.x+nx*drive.lateral,y=point.y+ny*drive.lateral;
    ctx.save();ctx.translate(x+2,y+2);ctx.rotate(angle);ctx.fillStyle='#0005';ctx.fillRect(-11,-5,22,10);ctx.restore();
    ctx.save();ctx.translate(x,y);ctx.rotate(angle);
    ctx.fillStyle='#111318';ctx.fillRect(-8,-7,6,4);ctx.fillRect(-8,3,6,4);ctx.fillRect(5,-7,6,4);ctx.fillRect(5,3,6,4);
    ctx.fillStyle='#d8ff38';ctx.beginPath();ctx.moveTo(13,0);ctx.lineTo(7,-3);ctx.lineTo(-4,-4);ctx.lineTo(-11,-2.5);ctx.lineTo(-11,2.5);ctx.lineTo(-4,4);ctx.lineTo(7,3);ctx.closePath();ctx.fill();
    ctx.fillRect(7,-6,2,12);ctx.fillRect(-11,-6,2,12);
    ctx.fillStyle='#101218';ctx.beginPath();ctx.ellipse(1,0,4,2.4,0,0,Math.PI*2);ctx.fill();
    ctx.fillStyle='#fff';ctx.fillRect(4,-.7,5,1.4);ctx.restore();
  }

  function draw(){
    const width=frame.clientWidth,height=frame.clientHeight,v=view();ctx.clearRect(0,0,width,height);if(drive.active&&drive.view==='driver'){drawDriverView(width,height);return}ctx.fillStyle='#f5f5f2';ctx.fillRect(0,0,width,height);drawGrid(width,height);ctx.save();ctx.translate(v.ox,v.oy);ctx.scale(v.scale,v.scale);
    const samples=sampleTrack();if(samples.length){const road=pathFromSamples(samples);ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#101218';ctx.lineWidth=state.width+state.edgeWidth;ctx.stroke(road);ctx.strokeStyle='#f8f8f6';ctx.lineWidth=state.width;ctx.stroke(road);if(state.showLine&&samples.length>1){const colors=palettes[state.palette]||palettes.classic;strokeSector(samples,0,state.sectors[1],colors[0]);strokeSector(samples,state.sectors[1],state.sectors[2],colors[1]);strokeSector(samples,state.sectors[2],1,colors[2]);drawSectorDivisions(samples)}if(state.closed){drawStartFinish(samples);state.markers.forEach((marker,index)=>drawMarker(marker,samples,index))}if(state.showNumbers)drawCornerNumbers();if(mode==='edit'||mode==='draw')state.points.forEach((point,index)=>{const active=index===hoverPoint||index===draggingPoint||index===selectedCorner;ctx.beginPath();ctx.arc(point.x,point.y,active?7:4,0,Math.PI*2);ctx.fillStyle=active?'#d8ff38':'#111318';ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.stroke();if(index===selectedCorner){ctx.strokeStyle='#d8ff38';ctx.lineWidth=1;ctx.beginPath();ctx.arc(point.x,point.y,11,0,Math.PI*2);ctx.stroke()}});if(mode==='draw'&&!state.closed&&state.points.length){const last=state.points[state.points.length-1];ctx.setLineDash([6,6]);ctx.strokeStyle='#777';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(pointer.x,pointer.y);ctx.stroke();ctx.setLineDash([]);if(state.autoConnect&&state.points.length>2){ctx.strokeStyle='#d8ff38';ctx.lineWidth=2;ctx.beginPath();ctx.arc(state.points[0].x,state.points[0].y,12,0,Math.PI*2);ctx.stroke()}}drawDriveCar(samples)}ctx.restore();
  }

  function nearestControl(point){let best=-1,distance=16;state.points.forEach((candidate,index)=>{const value=Math.hypot(candidate.x-point.x,candidate.y-point.y);if(value<distance){distance=value;best=index}});return best}
  function nearestMarker(point){if(!state.closed||!state.markers.length)return-1;const samples=sampleTrack(800);let best=-1,distance=18;state.markers.forEach((marker,index)=>{const anchor=pointOnTrack(marker.t,samples),value=Math.hypot(anchor.x-point.x,anchor.y-point.y);if(value<distance){distance=value;best=index}});return best}
  function setMode(next){if(drive.active&&next!=='drive'){drive.active=false;cancelAnimationFrame(drive.animation);drive.keys.clear();ui.driveHud.classList.add('hidden')}mode=next;document.querySelectorAll('.tool[data-mode]').forEach(button=>button.classList.toggle('active',button.dataset.mode===mode));ui.driveTool.classList.toggle('active',mode==='drive');const hints={draw:'CLICK TO ADD POINTS · DOUBLE-CLICK TO FINISH',sector:'CLICK THE CIRCUIT TO MOVE THE NEAREST SECTOR DIVISION',drs:'CLICK TO ADD · SELECT OR DRAG A MARKER TO EDIT',trap:'CLICK TO ADD · SELECT OR DRAG A MARKER TO EDIT'};ui.drawHint.classList.toggle('hidden',!hints[mode]);if(hints[mode])ui.drawHint.innerHTML=`<span class="pulse-dot"></span>${hints[mode]}`;canvas.style.cursor=mode==='edit'?'default':mode==='sector'?'pointer':mode==='drive'?'default':'crosshair';if(mode==='edit'){selectedMarker=-1;updateMarkerEditor()}draw()}
  function setRangeFill(element,min,max,value){const percent=((value-min)/(max-min))*100;element.style.background=`linear-gradient(90deg,var(--acid) ${percent}%,#343941 ${percent}%)`}
  function updateMarkerEditor(){const marker=state.markers[selectedMarker];ui.markerEditor.classList.toggle('hidden',!marker);if(!marker)return;ui.markerType.value=marker.type;ui.markerLabel.value=marker.label;ui.markerPosition.value=Math.round(marker.t*100);ui.markerPositionValue.value=`${Math.round(marker.t*100)}%`;setRangeFill(ui.markerPosition,0,100,marker.t*100)}
  function updateCornerEditor(){const valid=selectedCorner>=0&&selectedCorner<state.points.length,minimum=state.closed?3:2;ui.deleteCorner.disabled=!valid||state.points.length<=minimum;ui.cornerSelection.textContent=valid?`CORNER ${String(selectedCorner+1).padStart(2,'0')} SELECTED`:'SELECT A CORNER'}
  function deleteSelectedCorner(){if(selectedCorner<0||selectedCorner>=state.points.length){notify('Select a corner first');return}const minimum=state.closed?3:2;if(state.points.length<=minimum){notify(state.closed?'A closed circuit needs at least 3 corners':'Keep at least 2 points while drawing');return}const previous=clone(state),label=selectedCorner+1;state.points.splice(selectedCorner,1);selectedCorner=-1;hoverPoint=-1;commit(previous);notify(`Corner ${String(label).padStart(2,'0')} removed`)}
  function trackLengthKm(){const samples=sampleTrack(900);if(samples.length<2)return 0;let distance=0;for(let i=1;i<samples.length;i++)distance+=Math.hypot(samples[i].x-samples[i-1].x,samples[i].y-samples[i-1].y);if(state.closed)distance+=Math.hypot(samples[0].x-samples[samples.length-1].x,samples[0].y-samples[samples.length-1].y);return distance/1600}
  function updateUI(){ui.trackName.value=state.name;ui.profileName.value=state.name;ui.profileCode.value=state.profile.code;ui.profileCountry.value=state.profile.country;ui.profileLocation.value=state.profile.location;ui.profileDirection.value=state.profile.direction;ui.profileCodeDisplay.textContent=state.profile.code||'---';ui.profileCountryDisplay.textContent=state.profile.country||'---';ui.length.textContent=trackLengthKm().toFixed(3);ui.turns.textContent=state.points.length;ui.width.value=state.width;ui.widthValue.value=state.width;ui.edgeWidth.value=state.edgeWidth;ui.edgeWidthValue.value=state.edgeWidth;ui.racingWidth.value=state.racingWidth;ui.racingWidthValue.value=state.racingWidth;ui.numberToggle.checked=state.showNumbers;ui.autoConnectToggle.checked=state.autoConnect;ui.lineToggle.checked=state.showLine;ui.curbToggle.checked=state.showKerbs;ui.grid.classList.toggle('active',state.showGrid);ui.startDrive.disabled=!state.closed||state.points.length<3;ui.driveTool.disabled=ui.startDrive.disabled;ui.sector2Range.value=Math.round(state.sectors[1]*100);ui.sector3Range.value=Math.round(state.sectors[2]*100);ui.sector2Value.value=`${Math.round(state.sectors[1]*100)}%`;ui.sector3Value.value=`${Math.round(state.sectors[2]*100)}%`;setRangeFill(ui.width,16,32,state.width);setRangeFill(ui.edgeWidth,6,16,state.edgeWidth);setRangeFill(ui.racingWidth,2,6,state.racingWidth);setRangeFill(ui.sector2Range,8,84,state.sectors[1]*100);setRangeFill(ui.sector3Range,16,92,state.sectors[2]*100);document.querySelectorAll('.swatch').forEach(button=>button.classList.toggle('active',button.dataset.palette===state.palette));ui.undo.disabled=!history.length;ui.redo.disabled=!future.length;if(selectedMarker>=state.markers.length)selectedMarker=-1;if(selectedCorner>=state.points.length)selectedCorner=-1;updateMarkerEditor();updateCornerEditor();draw()}

  function formatDriveTime(seconds){const minutes=Math.floor(seconds/60),rest=seconds-minutes*60;return`${String(minutes).padStart(2,'0')}:${rest.toFixed(3).padStart(6,'0')}`}
  function updateDriveHud(){ui.driveSpeed.textContent=String(Math.round(drive.speed)).padStart(3,'0');ui.driveLap.textContent=String(drive.lap).padStart(2,'0');ui.driveTime.textContent=formatDriveTime(drive.elapsed)}
  function resetDrive(){drive.progress=state.profile.direction==='counterclockwise'?.999:0;drive.speed=0;drive.lateral=0;drive.steer=0;drive.braking=false;drive.lap=1;drive.elapsed=0;drive.lastLap=0;drive.lastFrame=performance.now();updateDriveHud();draw()}
  function driveFrame(timestamp){if(!drive.active)return;const dt=Math.min(.04,Math.max(0,(timestamp-drive.lastFrame)/1000));drive.lastFrame=timestamp;const throttle=drive.keys.has('ArrowUp')||drive.keys.has('w'),brake=drive.keys.has('ArrowDown')||drive.keys.has('s'),left=drive.keys.has('ArrowLeft')||drive.keys.has('a'),right=drive.keys.has('ArrowRight')||drive.keys.has('d');drive.braking=brake;if(throttle)drive.speed+=112*dt;if(brake)drive.speed-=225*dt;drive.speed-=(7+drive.speed*.018)*dt;drive.speed=Math.max(0,Math.min(335,drive.speed));const targetSteer=(right?1:0)-(left?1:0);drive.steer+=(targetSteer-drive.steer)*Math.min(1,dt*(targetSteer?12:7));const lateralLimit=Math.max(1,state.width/2-5.5);drive.lateral+=drive.steer*(7+drive.speed*.026)*dt;if(!targetSteer)drive.lateral*=Math.pow(.985,dt*60);drive.lateral=Math.max(-lateralLimit,Math.min(lateralLimit,drive.lateral));const worldLength=Math.max(1,trackLengthKm()*1600),direction=state.profile.direction==='counterclockwise'?-1:1;drive.progress+=direction*(drive.speed/2.25/worldLength)*dt;let crossed=false;if(drive.progress>=1){drive.progress-=1;crossed=true}else if(drive.progress<0){drive.progress+=1;crossed=true}drive.elapsed+=dt;if(crossed){drive.lastLap=drive.elapsed;drive.elapsed=0;drive.lap++;notify(`Lap ${drive.lap-1}: ${formatDriveTime(drive.lastLap)}`)}updateDriveHud();draw();drive.animation=requestAnimationFrame(driveFrame)}
  function startDrive(){if(drive.active){resetDrive();notify('Drive simulation restarted');return}if(!state.closed||state.points.length<3){notify('Close the circuit before driving');return}selectedMarker=-1;updateMarkerEditor();drive.active=true;setMode('drive');ui.driveHud.classList.remove('hidden');resetDrive();drive.animation=requestAnimationFrame(driveFrame);notify('Drive mode ready — press W or ↑ to accelerate')}
  function stopDrive(){if(!drive.active){setMode('edit');return}drive.active=false;cancelAnimationFrame(drive.animation);drive.keys.clear();ui.driveHud.classList.add('hidden');mode='edit';document.querySelectorAll('.tool[data-mode]').forEach(button=>button.classList.toggle('active',button.dataset.mode==='edit'));ui.driveTool.classList.remove('active');canvas.style.cursor='default';draw();notify('Drive simulation ended')}

  canvas.addEventListener('pointerdown',event=>{
    const point=toWorld(event);pointer=point;
    if(mode==='sector'&&state.points.length>2){const nearest=nearestTrack(point);if(nearest.distance>state.width+12){notify('Click closer to the circuit');return}const index=Math.abs(nearest.t-state.sectors[1])<=Math.abs(nearest.t-state.sectors[2])?1:2,previous=clone(state);state.sectors[index]=index===1?Math.max(.08,Math.min(state.sectors[2]-.08,nearest.t)):Math.min(.92,Math.max(state.sectors[1]+.08,nearest.t));commit(previous);notify(`Sector ${index+1} start moved`);return}
    if(mode==='drs'||mode==='trap'){const hit=nearestMarker(point);if(hit>=0){selectedMarker=hit;markerDragging=true;history.push(clone(state));future=[];canvas.setPointerCapture(event.pointerId);updateMarkerEditor();draw();notify('Drag along the circuit to reposition');return}if(!state.closed||state.points.length<3){notify('Finish the circuit before adding markers');return}const nearest=nearestTrack(point);if(nearest.distance>state.width+18){notify('Click closer to the circuit');return}const previous=clone(state),type=mode==='drs'?'drs':'trap',count=state.markers.filter(marker=>marker.type===type).length+1;state.markers.push({type,t:nearest.t,label:type==='drs'?`DRS\nZONE ${count}`:'SPEED\nTRAP'});selectedMarker=state.markers.length-1;commit(previous);notify(type==='drs'?'DRS zone placed':'Speed trap placed');return}
    if(mode==='edit'){const index=nearestControl(point);if(index>=0){selectedCorner=index;selectedMarker=-1;updateMarkerEditor();updateCornerEditor();draggingPoint=index;history.push(clone(state));future=[];canvas.setPointerCapture(event.pointerId);draw()}return}
    if(mode==='draw'){if(state.autoConnect&&state.points.length>=3&&Math.hypot(point.x-state.points[0].x,point.y-state.points[0].y)<20){const previous=clone(state);state.closed=true;commit(previous);setMode('edit');notify('Start and finish connected automatically');return}const previous=clone(state);if(state.closed){state.points=[];state.markers=[];state.sectors=[0,.334,.667];state.closed=false}state.points.push(point);commit(previous)}
  });
  canvas.addEventListener('pointermove',event=>{pointer=toWorld(event);if(markerDragging&&selectedMarker>=0){state.markers[selectedMarker].t=nearestTrack(pointer).t;updateMarkerEditor();draw();return}if(draggingPoint>=0){state.points[draggingPoint]=pointer;draw();return}if(mode==='edit'){hoverPoint=nearestControl(pointer);canvas.style.cursor=hoverPoint>=0?'grab':'default';draw()}else if(mode==='draw')draw()});
  canvas.addEventListener('pointerup',event=>{if(markerDragging){markerDragging=false;save();updateUI();try{canvas.releasePointerCapture(event.pointerId)}catch{}}if(draggingPoint>=0){draggingPoint=-1;save();updateUI();try{canvas.releasePointerCapture(event.pointerId)}catch{}}});
  canvas.addEventListener('dblclick',event=>{if(mode!=='draw'||state.points.length<3)return;event.preventDefault();state.points.pop();state.closed=state.autoConnect;save();updateUI();setMode('edit');notify(state.closed?'Circuit auto-connected — ready to race':'Open track finished with three sectors')});

  document.querySelectorAll('.tool[data-mode]').forEach(button=>button.addEventListener('click',()=>setMode(button.dataset.mode)));
  ui.driveTool.addEventListener('click',startDrive);ui.startDrive.addEventListener('click',startDrive);$('exitDriveBtn').addEventListener('click',stopDrive);
  document.querySelectorAll('[data-drive-view]').forEach(button=>button.addEventListener('click',()=>{drive.view=button.dataset.driveView;document.querySelectorAll('[data-drive-view]').forEach(item=>item.classList.toggle('active',item.dataset.driveView===drive.view));draw()}));
  document.querySelectorAll('.swatch').forEach(button=>button.addEventListener('click',()=>{const previous=clone(state);state.palette=button.dataset.palette;commit(previous)}));
  ui.width.addEventListener('input',()=>{state.width=+ui.width.value;ui.widthValue.value=state.width;setRangeFill(ui.width,16,32,state.width);save();draw()});
  ui.edgeWidth.addEventListener('input',()=>{state.edgeWidth=+ui.edgeWidth.value;ui.edgeWidthValue.value=state.edgeWidth;setRangeFill(ui.edgeWidth,6,16,state.edgeWidth);save();draw()});
  ui.racingWidth.addEventListener('input',()=>{state.racingWidth=+ui.racingWidth.value;ui.racingWidthValue.value=state.racingWidth;setRangeFill(ui.racingWidth,2,6,state.racingWidth);save();draw()});
  ui.numberToggle.addEventListener('change',()=>{state.showNumbers=ui.numberToggle.checked;save();draw()});ui.autoConnectToggle.addEventListener('change',()=>{state.autoConnect=ui.autoConnectToggle.checked;save();draw();notify(state.autoConnect?'Auto-connect enabled':'Auto-connect disabled')});ui.lineToggle.addEventListener('change',()=>{state.showLine=ui.lineToggle.checked;save();draw()});ui.curbToggle.addEventListener('change',()=>{state.showKerbs=ui.curbToggle.checked;save();draw()});
  ui.grid.addEventListener('click',()=>{state.showGrid=!state.showGrid;save();updateUI()});$('fitBtn').addEventListener('click',()=>notify('Track fitted to canvas'));
  ui.trackName.addEventListener('input',()=>{state.name=ui.trackName.value.toUpperCase();ui.profileName.value=state.name;save()});ui.profileName.addEventListener('input',()=>{state.name=ui.profileName.value.toUpperCase();ui.profileName.value=state.name;ui.trackName.value=state.name;save()});ui.profileCode.addEventListener('input',()=>{state.profile.code=ui.profileCode.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,3);ui.profileCode.value=state.profile.code;ui.profileCodeDisplay.textContent=state.profile.code||'---';save()});ui.profileCountry.addEventListener('input',()=>{state.profile.country=ui.profileCountry.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,3);ui.profileCountry.value=state.profile.country;ui.profileCountryDisplay.textContent=state.profile.country||'---';save()});ui.profileLocation.addEventListener('input',()=>{state.profile.location=ui.profileLocation.value.toUpperCase();ui.profileLocation.value=state.profile.location;save()});ui.profileDirection.addEventListener('change',()=>{state.profile.direction=ui.profileDirection.value;save();notify(`${ui.profileDirection.options[ui.profileDirection.selectedIndex].text} layout`)});
  ui.sector2Range.addEventListener('input',()=>{state.sectors[1]=Math.min(+ui.sector2Range.value/100,state.sectors[2]-.08);updateUI();save()});ui.sector3Range.addEventListener('input',()=>{state.sectors[2]=Math.max(+ui.sector3Range.value/100,state.sectors[1]+.08);updateUI();save()});$('resetSectorsBtn').addEventListener('click',()=>{const previous=clone(state);state.sectors=[0,.334,.667];commit(previous);notify('Sectors split evenly')});
  ui.markerType.addEventListener('change',()=>{const marker=state.markers[selectedMarker];if(!marker)return;marker.type=ui.markerType.value;if(marker.type==='drs'&&!marker.label.includes('DRS'))marker.label='DRS\nZONE';if(marker.type==='trap'&&!marker.label.includes('TRAP'))marker.label='SPEED\nTRAP';save();updateUI()});ui.markerLabel.addEventListener('input',()=>{const marker=state.markers[selectedMarker];if(!marker)return;marker.label=ui.markerLabel.value.toUpperCase();save();draw()});ui.markerPosition.addEventListener('input',()=>{const marker=state.markers[selectedMarker];if(!marker)return;marker.t=+ui.markerPosition.value/100;updateMarkerEditor();save();draw()});$('closeMarkerBtn').addEventListener('click',()=>{selectedMarker=-1;updateMarkerEditor();draw()});$('deleteMarkerBtn').addEventListener('click',()=>{if(selectedMarker<0)return;const previous=clone(state);state.markers.splice(selectedMarker,1);selectedMarker=-1;commit(previous);notify('Marker removed')});ui.deleteCorner.addEventListener('click',deleteSelectedCorner);
  $('resetBtn').addEventListener('click',()=>{const previous=clone(state);state=defaultState();selectedMarker=-1;commit(previous);setMode('edit');notify('Demo circuit restored')});$('newBtn').addEventListener('click',()=>{const previous=clone(state);state.points=[];state.markers=[];state.sectors=[0,.334,.667];state.closed=false;selectedMarker=-1;commit(previous);setMode('draw');notify('Click the canvas to begin')});

  function undo(){if(!history.length)return;future.push(clone(state));state=normalizeState(history.pop());selectedMarker=-1;save();updateUI()}
  function redo(){if(!future.length)return;history.push(clone(state));state=normalizeState(future.pop());selectedMarker=-1;save();updateUI()}
  ui.undo.addEventListener('click',undo);ui.redo.addEventListener('click',redo);
  window.addEventListener('keydown',event=>{const key=event.key.length===1?event.key.toLowerCase():event.key;if(drive.active&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(key)){event.preventDefault();drive.keys.add(key);return}if(drive.active&&key==='r'){event.preventDefault();resetDrive();notify('Lap restarted');return}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();event.shiftKey?redo():undo();return}if(event.key==='Escape'){drive.active?stopDrive():setMode('edit');return}if(!['Delete','Backspace'].includes(event.key)||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;if(selectedMarker>=0){const previous=clone(state);state.markers.splice(selectedMarker,1);selectedMarker=-1;commit(previous);notify('Marker removed')}else if(selectedCorner>=0||hoverPoint>=0){if(selectedCorner<0)selectedCorner=hoverPoint;deleteSelectedCorner()}});
  window.addEventListener('keyup',event=>{const key=event.key.length===1?event.key.toLowerCase():event.key;drive.keys.delete(key)});window.addEventListener('blur',()=>drive.keys.clear());
  document.querySelectorAll('[data-drive-key]').forEach(button=>{const key=button.dataset.driveKey;const press=event=>{event.preventDefault();drive.keys.add(key);button.setPointerCapture?.(event.pointerId)};const release=event=>{event.preventDefault();drive.keys.delete(key)};button.addEventListener('pointerdown',press);button.addEventListener('pointerup',release);button.addEventListener('pointercancel',release);button.addEventListener('pointerleave',release)});
  function exportPng(){const output=document.createElement('canvas');output.width=canvas.width;output.height=canvas.height;const exportCtx=output.getContext('2d');exportCtx.drawImage(canvas,0,0);const scale=Math.max(.55,Math.min(1.5,output.width/1440)),boxWidth=250*scale,boxHeight=58*scale,x=output.width-boxWidth-18*scale,y=output.height-boxHeight-18*scale;exportCtx.save();exportCtx.fillStyle='rgba(16,18,24,.88)';exportCtx.fillRect(x,y,boxWidth,boxHeight);exportCtx.fillStyle='#d8ff38';for(let i=0;i<3;i++)exportCtx.fillRect(x+15*scale,y+(15+i*9)*scale,(30-i*7)*scale,5*scale);exportCtx.fillStyle='#fff';exportCtx.font=`800 ${18*scale}px Manrope,Arial`;exportCtx.textBaseline='middle';exportCtx.fillText('APEX',x+58*scale,y+23*scale);exportCtx.fillStyle='#8e969f';exportCtx.font=`600 ${7*scale}px "DM Mono",monospace`;exportCtx.fillText('TRACK STUDIO  /  '+state.profile.code,x+58*scale,y+39*scale);exportCtx.restore();const link=document.createElement('a');link.download=`${state.name.toLowerCase().replace(/[^a-z0-9]+/g,'-')||'apex-track'}.png`;link.href=output.toDataURL('image/png');link.click();notify('Watermarked PNG exported')}
  $('exportBtn').addEventListener('click',exportPng);
  window.addEventListener('resize',resize);updateUI();resize();
})();
